# Create a Logging bucket with log analytics enabled
resource "google_logging_project_bucket_config" "logging_bucket" {
  project         = var.project_id
  location        = var.region
  bucket_id       = local.resource_names.logging_bucket
  description     = "GTM Monitoring Logs"
  retention_days  = var.log_retention_days
  
  enable_analytics = true
  
  depends_on = [google_project_service.logging_api]
}

# Create necessary service accounts before attempting to use them
resource "google_project_service_identity" "logging_service_account" {
  provider = google-beta
  project  = var.project_id
  service  = "logging.googleapis.com"
  
  depends_on = [google_project_service.logging_api]
}

# Create a logs sink for the Logging bucket
resource "google_logging_project_sink" "logging_sink" {
  name        = local.resource_names.logging_sink
  destination = "logging.googleapis.com/projects/${var.project_id}/locations/${var.region}/buckets/${local.resource_names.logging_bucket}"
  filter      = "resource.type=\"http_load_balancer\" AND resource.labels.forwarding_rule_name=\"${local.resource_names.forwarding_rule}\""

  # Use a unique writer identity generated by GCP
  unique_writer_identity = true
  
  depends_on = [
    google_logging_project_bucket_config.logging_bucket,
    google_compute_global_forwarding_rule.tag_monitoring_https_rule
  ]
}

# Grant necessary IAM roles to the service account generated by the sink
resource "google_project_iam_member" "logging_sink_writer" {
  project = var.project_id
  role    = "roles/logging.bucketWriter"
  member  = coalesce(
    google_project_service_identity.logging_service_account.member,
    "serviceAccount:service-${data.google_project.current.number}@gcp-sa-logging.iam.gserviceaccount.com"
  )
  
  depends_on = [
    google_logging_project_sink.logging_sink,
    google_project_service_identity.logging_service_account
  ]
}

# 14. Create a logging linked dataset
resource "google_logging_linked_dataset" "logging_linked_dataset" {
  link_id     = "tag_monitoring_log_link"
  bucket      = local.resource_names.logging_bucket
  parent      = "projects/${var.project_id}"
  location    = var.region
  description = "Linked dataset for GTM Monitoring Logs"
  
  depends_on = [google_logging_project_bucket_config.logging_bucket]
}